### ISSUE TITLE
Archive API 404 not found

### ISSUE THREAD

**Issue by aalirezamoradii** [groupe-edf/nexus-repository-dart#12]
test on nexus 3.38.0, 3.38.1, 3.39.0 and latest(3.68.0) version

package api worked

![Screenshot 2024-05-11 at 02 56 34](https://github.com/groupe-edf/nexus-repository-dart/assets/56014923/b8e1cdd7-933a-4f66-9856-0accb26c5916)

**Comment by npu3pak** [comment]
https://github.com/npu3pak/nexus-repository-dart-2024/releases/tag/2.0.0
Made the fork with hotfix

**Comment by aalirezamoradii** [comment]
> https://github.com/npu3pak/nexus-repository-dart-2024/releases/tag/2.0.0 Made the fork with hotfix

Thanks

**Comment by mat1e** [comment]
Fixed in v1.1.1
