### ISSUE TITLE
Many packages are not getting downloaded

### ISSUE THREAD

**Issue by mayankmajorwar5** [groupe-edf/nexus-repository-dart#14]
I am trying to create a base image of flutter with version 3.13.2. During installation of package example melos, we are facing issue from nexus. Some packages are getting downloaded some are not. I am in an airgapped environment and using sonatype nexus is mandatory for me. Requesting your help here.

**Comment by mat1e** [comment]
Can you provide the error when the package is not downloaded

**Comment by mayankmajorwar5** [comment]
Dear @mat1e ,
Thank you for your reply. The error was 404 and you have already fixed it in the latest release. Thank you so much. Much appreciated.
